# Embedded file name: scripts/client/gui/Scaleform/daapi/settings/tooltips.py
from gui.Scaleform.managers.ToolTipManager import ToolTipManager
__author__ = 'd_trofimov'
TOOLTIPS = {'tankman': {'tooltip': 'ToolTipTankmenUI',
             'method': ToolTipManager.getTankmanData,
             'complex': None},
 'battleStatsAchievementData': {'tooltip': 'ToolTipAchievementUI',
                                'method': ToolTipManager.getBattleResultsAchievementData,
                                'complex': None},
 'achievement': {'tooltip': 'ToolTipAchievementUI',
                 'method': ToolTipManager.getAchievmentData,
                 'complex': None},
 'globalRating': {'tooltip': 'ToolTipAchievementUI',
                  'method': ToolTipManager.getGlobalRatingData,
                  'complex': None},
 'achievementAttr': {'tooltip': 'ToolTipAchievementUI',
                     'method': ToolTipManager.getAchieveAttrData,
                     'complex': None},
 'tankClass': {'tooltip': 'ToolTipTankClassUI',
               'method': ToolTipManager.getBattleResultsAchievementData,
               'complex': None},
 'carouselVehicle': {'tooltip': 'TooltipVehicleUI',
                     'method': ToolTipManager.getCarouselVehicleData,
                     'complex': None},
 'inventoryVehicle': {'tooltip': 'TooltipVehicleUI',
                      'method': ToolTipManager.getInventoryVehicleData,
                      'complex': None},
 'techtreeVehicle': {'tooltip': 'TooltipVehicleUI',
                     'method': ToolTipManager.getTechTreeVehicleData,
                     'complex': None},
 'inventoryShell': {'tooltip': 'ToolTipEquipmentUI',
                    'method': ToolTipManager.getInventoryShellData,
                    'complex': None},
 'inventoryModule': {'tooltip': 'ToolTipEquipmentUI',
                     'method': ToolTipManager.getInventoryModuleData,
                     'complex': None},
 'techMainModule': {'tooltip': 'ToolTipEquipmentUI',
                    'method': ToolTipManager.getTechMainModuleData,
                    'complex': None},
 'hangarModule': {'tooltip': 'ToolTipEquipmentUI',
                  'method': ToolTipManager.getHangarModuleData,
                  'complex': None},
 'techtreeModule': {'tooltip': 'ToolTipEquipmentUI',
                    'method': ToolTipManager.getTechTreeModuleData,
                    'complex': None},
 'shopVehicle': {'tooltip': 'TooltipVehicleUI',
                 'method': ToolTipManager.getShopVehicleData,
                 'complex': None},
 'shopShell': {'tooltip': 'ToolTipEquipmentUI',
               'method': ToolTipManager.getShopShellData,
               'complex': None},
 'hangarShell': {'tooltip': 'ToolTipEquipmentUI',
                 'method': ToolTipManager.getHangarShellData,
                 'complex': None},
 'techMainShell': {'tooltip': 'ToolTipEquipmentUI',
                   'method': ToolTipManager.getTechMainShellData,
                   'complex': None},
 'shopModule': {'tooltip': 'ToolTipEquipmentUI',
                'method': ToolTipManager.getShopModuleData,
                'complex': None},
 'tankmanSkill': {'tooltip': 'ToolTipSkillUI',
                  'method': ToolTipManager.getTankmanSkillData,
                  'complex': None},
 'tankmanNewSkill': {'tooltip': 'ToolTipBuySkillUI',
                     'method': ToolTipManager.getTankmanNewSkillData,
                     'complex': lambda tooltipData: tooltipData['count'] > 1 or tooltipData['level'] > 0},
 'efficiencyParam': {'tooltip': 'ToolTipFinalStatsUI',
                     'method': ToolTipManager.getEfficiencyParam,
                     'complex': None},
 'rssNews': {'tooltip': 'ToolTipRSSNewsUI',
             'method': None,
             'complex': None},
 'igrInfo': {'tooltip': 'ToolTipIGRUI',
             'method': ToolTipManager.getIgrInfo,
             'complex': None},
 'default': {'tooltip': 'ToolTipComplexUI',
             'method': None,
             'complex': None}}