# 2013.11.15 11:27:30 EST
# Embedded file name: scripts/common/arena_achievements.py
from dossiers2.custom.records import RECORD_DB_IDS
ACHIEVEMENTS = ('warrior', 'invader', 'sniper', 'defender', 'steelwall', 'supporter', 'scout', 'evileye', 'medalWittmann', 'medalOrlik', 'medalOskin', 'medalHalonen', 'medalBurda', 'medalBillotte', 'medalKolobanov', 'medalFadin', 'medalRadleyWalters', 'medalLafayettePool', 'medalLehvaslaiho', 'medalNikolas', 'medalPascucci', 'medalDumitru', 'medalBrunoPietro', 'medalTarczay', 'heroesOfRassenay', 'medalDeLanglade', 'medalTamadaYoshio', 'raider', 'kamikaze', 'huntsman', 'bombardier', 'luckyDevil', 'ironMan', 'sturdy', 'alaric', 'lumberjack', 'medalBrothersInArms', 'medalCrucialContribution')
ACHIEVEMENTS_WITH_REWARD = set([ RECORD_DB_IDS['achievements', name] for name in ('warrior', 'invader', 'sniper', 'defender', 'steelwall', 'supporter', 'scout', 'evileye', 'heroesOfRassenay', 'medalFadin', 'medalNikolas', 'medalPascucci', 'medalLehvaslaiho', 'medalRadleyWalters', 'medalHalonen', 'medalDumitru', 'medalDeLanglade', 'medalOrlik', 'medalOskin', 'medalLafayettePool', 'medalBurda', 'medalTamadaYoshio', 'medalBrothersInArms', 'medalCrucialContribution') ])
INBATTLE_SERIES = ('sniper', 'killing', 'piercing')
INBATTLE_SERIES_INDICES = dict(((x[1], x[0]) for x in enumerate(INBATTLE_SERIES)))
_BILLOTTE_CMN_CNDS = {'hpPercentage': 20,
 'minCrits': 5}
ACHIEVEMENT_CONDITIONS = {'warrior': {'minFrags': 6},
 'invader': {'minCapturePts': 80},
 'sniper': {'minAccuracy': 0.85,
            'minShots': 10,
            'minDamage': 1000},
 'defender': {'minPoints': 70},
 'steelwall': {'minDamage': 1000,
               'minHits': 11},
 'supporter': {'minAssists': 6},
 'scout': {'minDetections': 9},
 'evileye': {'minAssists': 6},
 'medalRadleyWalters': {'minLevel': 5,
                        'minKills': 8,
                        'maxKills': 9},
 'medalLafayettePool': {'minLevel': 5,
                        'minKills': 10,
                        'maxKills': 13},
 'heroesOfRassenay': {'minKills': 14,
                      'maxKills': 255},
 'medalOrlik': {'minVictimLevelDelta': 2,
                'minKills': 3},
 'medalLehvaslaiho': {'minVictimLevelDelta': 2,
                      'minKills': 2,
                      'maxKills': 2},
 'medalOskin': {'minVictimLevelDelta': 2,
                'minKills': 3,
                'maxKills': 3},
 'medalNikolas': {'minVictimLevelDelta': 2,
                  'minKills': 4,
                  'maxKills': 255},
 'medalHalonen': {'minVictimLevelDelta': 2,
                  'minKills': 3},
 'medalPascucci': {'minKills': 3,
                   'maxKills': 3},
 'medalDumitru': {'minKills': 4,
                  'maxKills': 4},
 'medalBurda': {'minKills': 5,
                'maxKills': 255},
 'medalBillotte': {'cmn_cnds': _BILLOTTE_CMN_CNDS,
                   'minKills': 2,
                   'maxKills': 2},
 'medalBrunoPietro': {'cmn_cnds': _BILLOTTE_CMN_CNDS,
                      'minKills': 3,
                      'maxKills': 4},
 'medalTarczay': {'cmn_cnds': _BILLOTTE_CMN_CNDS,
                  'minKills': 5,
                  'maxKills': 255},
 'medalKolobanov': {'teamDiff': 5},
 'medalBrothersInArms': {'minKills': 3},
 'medalCrucialContribution': {'minKills': 12},
 'medalDeLanglade': {'minKills': 4},
 'medalTamadaYoshio': {'minKills': 3,
                       'maxKills': 255,
                       'minVictimLevelDelta': 2},
 'kamikaze': {'levelDelta': 1},
 'huntsman': {'minKills': 3},
 'bombardier': {'minKills': 2},
 'luckyDevil': {'radius': 10.99},
 'ironMan': {'minHits': 10},
 'sturdy': {'minHealth': 10.0},
 'alaric': {'minKills': 2,
            'minMonuments': 1},
 'lumberjack': {'minKills': 3,
                'minTrees': 30}}
# okay decompyling res/scripts/common/arena_achievements.pyc 
# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
# 2013.11.15 11:27:30 EST
